name: Run Llama3.2-Vision Chatbot

on:
  push: # Runs automatically when changes are pushed to the main branch
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  run-chatbot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl python3 python3-pip
          curl -sSL https://ollama.ai/install | bash
          ollama pull llama3.2-vision

      - name: Run Chatbot Script
        run: |
          python chatbot.py
